title: STEEL Team
title_separator: "-"
description: Home page of the Ethereum Foundation STEEL Team
remote_theme: pages-themes/hacker@v0.2.0
baseurl: /steel_site_demo
url: https://carsons-eels.github.io
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
- README.md
- CONTACT.md
locale: "en-ES"
